name: wave_projekt
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'


environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  path: ^1.8.0
  test: ^1.21.0
  ffigen: ^7.2.7

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1

  
